### ISSUE TITLE
No import for 'tree' export in export { tree };

### ISSUE THREAD

**Issue by thespacedeck** [mljs/distance#14]
Upon installing node_modules/ml-distance/lib/similarities.d.ts:1:10 - error TS2304: Cannot find name 'tree'.

seems like it is missing the import for `import * as tree from 'ml-tree-similarity';`

checkout: https://www.npmjs.com/package/ml-distance?activeTab=code

**Comment by zreecespieces** [comment]
Can confirm I also am running into this error.
